---
- name: Install and configure nginx for static website hosting
  hosts: all
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Start Service
      apt:
        name: nginx
        state: present