---
- name: Install and configure nginx for static website hosting
  hosts: all
  become: false

  tasks:
    - name: Install apache
      apt:
        name: httpd
        state: latest

    - name: Start Service #abcd
      apt:
        name: httpd
        state: present